title: Jonathan (Wiggy)
logo: /assets/histogram-example-2.png
#description
show_downloads: true
theme: jekyll-theme-hydejack

accent_image:          /assets/img/histogram-example-2.png
accent_color:          rgb(79,177,186)

theme_color:           rgb(25,55,71)

defaults:
  # You can use this to provide a default accent color and background for
  # all pages under a given path:
  - scope:
      path:            hyde/
    values:
      accent_color:    rgb(38,139,210)
      theme_color:     rgb(32,32,32)
      accent_image:
        background:    rgb(32,32,32)
        overlay:       false

  # Don't include documents in assets in the sitemap
  - scope:
      path:            assets/
    values:
      sitemap:         false

hydejack:
  # Configure the order of complementary content on blog posts
  post_addons:         [about, newsletter, related, random, comments]

  # Configure the order of complementary content on project pages
  project_addons:      [about, newsletter, other, comments]

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external:    false

  # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state:       false

  # Set to `true` if you want to disable the drawer
  no_drawer:           false

  # Set to `true` if you don't to use the auto-hiding (JavaScript based) navbar.
  # Note that this will not hide the navbar completely, only replace it with a static one.
  # Use custom css to hide completely, e.g. `#_navbar { display: none }`.
  no_navbar:           false

  # Set to true to disable the built-in search functionality.
  # Note that search is disabled during local use to save on build time.
  # Run Jekyll with the `JEKYLL_ENV` environment variable set to `production` to enable.
  no_search:           false

  # Set to `true` if you do not want parts of the css inlined in <head/>
  # This will increase site build speed dramatically!
  no_inline_css:       false

  # Set to `true` if you don't intend on changing the accent color on a per-page basis. 
  # This will increase site build speed!
  no_page_style:       false

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout:     true

  # Set to `true` to disable the dynamic Table of Contents on large screens.
  no_toc:              false

  # When set to `true`, will not extend the content in the "third column" on large screens.
  # Instead, all content will remains within the center column.
  # Note that this will not affect the Table of Contents, use `no_toc` instead.
  no_third_column:     false

  # Set to `true` if you don't like oversized headlines on large screens.
  no_large_headings:   false

  # Set to `true` if you do not want to expose your resume and projects
  # in machine-readable formats.
  no_structured_data:  false

  # You can set this to `true` if you don't want to set the `theme-color` meta tag,
  # This only affects the meta tag, not the color specified in the app manifest.
  no_theme_color:      false

  # Disable the breadcrumbs above the title
  no_breadcrumbs:      false

  # Set to `true` when building with the `--lsi` option.
  # The net effect is to use the Jekyll-provided `site.related_posts` variable.
  use_lsi:             true

  # When using Google Analytics, set to `true` to display a cookie notice banner.
  # When enabled, no user-related data will be stored until the user gives consent.
  cookies_banner:      false

  # Set to `true` if you would like to add a "Powered by Hydejack" link in the footer.
  # Note that this setting has no effect when using the free version.
  advertise:           false

  # Buyers of the PRO version can opt to hide all dates from the theme.
  # Frequent consumers of online content will know that nothing devalues a post like
  # seeing an old date. 
  hide_dates:          false

  # Similarly, showing last modified date can devalue a post if it is too far in the past.
  hide_last_modified:  false

  # Note that dark mode only works in the PRO version of Hydejack.
  dark_mode:
    # Set to `true` to always use the dark theme.
    always:            false

    # Set to `true` to use the dark theme based on visitors' preference (OS setting).
    dynamic:           true

    # Set to `true` to allow visitors to switch between light and dark mode.
    icon:              true

#page-col: "#FFFFFF"
#text-col: "#404040"
#link-col: "#008AFF"
#hover-col: "#0085A1"
#navbar-col: "#EAEAEA"
#navbar-text-col: "#404040"
#navbar-border-col: "#DDDDDD"
#footer-col: "#EAEAEA"
#footer-text-col: "#777777"
#footer-link-col: "#404040"
#footer-hover-col: "#0085A1"

